### ISSUE TITLE
`Client::room_send` broken

### ISSUE THREAD

**Issue by LorenzSchueler** [matrix-org/matrix-rust-sdk#166]
I've just pulled the latest changes form master. After adjusting the changed types my bot compiles again. However when I try to send a message with `Client::room_send` I get the following error. This was not the case before I pulled the changes (before I build against master form about 2 weeks ago)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MatrixError(OlmError(Store(Serialization(Error("missing field `history_visibility`", line: 1, column: 462)))))', rust_matrix_client/src/main.rs:115:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: <rust_matrix_client::CommandBot as matrix_sdk_base::event_handler::EventHandler>::on_room_message::__on_room_message::{{closure}}
             at ./rust_matrix_client/src/main.rs:112:29
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
   7: matrix_sdk_base::event_handler::Handler::handle_timeline_event::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk_base/src/event_handler/mod.rs:142:56
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   9: matrix_sdk_base::event_handler::Handler::handle_sync::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk_base/src/event_handler/mod.rs:89:21
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: matrix_sdk_base::client::BaseClient::receive_sync_response::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk_base/src/client.rs:938:13
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: matrix_sdk::client::Client::sync_once::{{closure}}::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk/src/client.rs:1674:12
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.23/src/instrument.rs:151:9
  16: matrix_sdk::client::Client::sync_once::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk/src/client.rs:1658:92
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  18: matrix_sdk::client::Client::sync_with_callback::{{closure}}::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk/src/client.rs:1765:28
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.23/src/instrument.rs:151:9
  21: matrix_sdk::client::Client::sync_with_callback::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk/src/client.rs:1756:5
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  23: matrix_sdk::client::Client::sync::{{closure}}
             at /home/lorenz/Dokumente/programming/rust/matrix/matrix-rust-sdk/matrix_sdk/src/client.rs:1690:9
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  25: rust_matrix_client::login::{{closure}}
             at ./rust_matrix_client/src/main.rs:276:9
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27: rust_matrix_client::main::{{closure}}
             at ./rust_matrix_client/src/main.rs:298:5
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  29: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/park/thread.rs:263:54
  30: tokio::coop::with_budget::{{closure}}
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121:9
  31: std::thread::local::LocalKey<T>::try_with
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  32: std::thread::local::LocalKey<T>::with
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  33: tokio::coop::with_budget
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114:5
  34: tokio::coop::budget
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98:5
  35: tokio::park::thread::CachedParkThread::block_on
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/park/thread.rs:263:31
  36: tokio::runtime::enter::Enter::block_on
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/enter.rs:151:13
  37: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/mod.rs:71:9
  38: tokio::runtime::Runtime::block_on
             at /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/mod.rs:452:43
  39: rust_matrix_client::main
             at ./rust_matrix_client/src/main.rs:290:1
  40: core::ops::function::FnOnce::call_once
             at /home/lorenz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```
I don't really understand the error because the room has a ` matrix_sdk::events::room::history_visibility::HistoryVisibility` set.

I'd really appreciate if you could help me get this working again.

**Comment by poljar** [comment]
The storage layer isn't stable yet and there are no migrations, the `HistoryVisibility` is nowadays stored with room keys.

You'll have to clear your store and recreate your device.

**Comment by LorenzSchueler** [comment]
That solved it. 
Thanks :)
