### ISSUE TITLE
Error parsing error response for `POST /_matrix/client/v3/keys/signatures/upload`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-rust-sdk#2205]
My client is stuck in a loop:

```
rust-crypto: successfully made HTTP request: POST /_matrix/client/v3/keys/signatures/upload
18:24:58.559 react_devtools_backend_compact.js:2367 Error processing outgoing-message requests from rust crypto-sdk Error: deserialization failed: missing field `error` at line 1 column 128
    at push.1685.module.exports.__wbindgen_error_new (matrix_sdk_crypto_js.js:6676:1)
    at <wasm_bindgen::JsError as core::convert::From<E>>::from::h66f6a8cb01617678 (01b16b46:0x313e37)
    at <matrix_sdk_crypto_js::responses::OwnedResponse as core::convert::TryFrom<(matrix_sdk_crypto_js::requests::RequestType,http::response::Response<alloc::vec::Vec<u8>>)>>::try_from::hde971358fe62519b (01b16b46:0x19b93b)
    at olmmachine_markRequestAsSent (01b16b46:0x2118e1)
    at OlmMachine.markRequestAsSent (matrix_sdk_crypto_js.js:3221:1)
    at OutgoingRequestProcessor.makeOutgoingRequest (OutgoingRequestProcessor.ts:99:35)
    at async RustCrypto.outgoingRequestLoop (rust-crypto.ts:876:21)
```

Synapse is returning a response like this:

```json
{
    "failures": {
        "@richvdh:sw1v.org": {
            "EOZDSWJVGZ": {
                "status": 400,
                "errcode": "M_INVALID_SIGNATURE",
                "message": "400: Invalid signature"
            }
        }
    }
}
```

There is no `error` property, and the [spec](https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3keyssignaturesupload) does not specify one (though the example rather implies that it should be there).

See also https://github.com/matrix-org/matrix-spec/issues/1594.

**Comment by jplatte** [comment]
The parsing is done by Ruma, but I don't seem to be able to move the issue. Can you open a fresh one there and close this one?

**Comment by richvdh** [comment]
Have opened https://github.com/ruma/ruma/issues/1591. Please can we keep this open as well though: from an application's POV it's a bug in the matrix rust SDK, even if the root cause of that bug is in an underlying library.

**Comment by Hywan** [comment]
Seems fixed in Ruma. Closing this issue.

**Comment by jplatte** [comment]
We didn't upgrade Ruma yet since the fix was merged.
